### ISSUE TITLE
Wrong ingress annotation indentation for multiline annotations in values

### ISSUE THREAD

**Issue by vhurtevent** [OctoPerf/helm-charts#10]
Hello,

I'm testing the Octoperf helm chart and I hit a problem when trying to set multiline ingress.annotations values.

For exemple, I want to set 

```
ingress:
  enabled: true
  className: nginx

  annotations:
    cert-manager.io/cluster-issuer: my-cluster-issuer
    kubernetes.io/tls-acme: "true"
```
But, at template generation, the second line of annotation loses indent when using the existing template :

```
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  {{- with .Values.ingress.annotations }}
  {{ toYaml . | indent 2 }}
  {{- end }}
```
