### ISSUE TITLE
warning: cannot overwrite table with non table for initContainers (map[])

### ISSUE THREAD

**Issue by PaulEvans8669** [OctoPerf/helm-charts#12]
Hello,

I'm currently facing an issue where overriding some values in the values.yaml throws a warning.

I am trying to override the `backend.volumes = {}` and `backend.initContainers = {}` with a list of volumes and initContainers as such :

```yaml
backend:

    volumes:
      - name: my-configmap-volume
        configMap:
          name: my-configmap

    initContainers:
      - name: my-sidecat
        image: my-image:tag
        <...>
```

Running `helm template --debug my-chart . -f config/custom-values.yaml > test.txt`  throws the following warning : 

```
coalesce.go:200: warning: cannot overwrite table with non table for initContainers (map[])
coalesce.go:200: warning: cannot overwrite table with non table for volumes (map[])
coalesce.go:200: warning: cannot overwrite table with non table for volumes (map[])
coalesce.go:200: warning: cannot overwrite table with non table for initContainers (map[])
coalesce.go:200: warning: cannot overwrite table with non table for initContainers (map[])
coalesce.go:200: warning: cannot overwrite table with non table for volumes (map[])
```

I believe this occurs as the default values for `backend.volumes` and `backend.initContainers` are object `{}`, not arrays `[]`.
These are the only occurences of this issue that I have faced for the moment, but i believe there are other possible fields that would throw the same error (such as `backend.volumeMounts`).

Note, this only throws a warning, and the template is correctly interpreted with arrays, but I can only imagine this breaking at some point in a close future.

**Comment by jloisel** [comment]
Hi,

Do you have any idea how we can fix this? If possible, can you make a pull request?

Thanks :)

**Comment by jloisel** [comment]
Can you try something like this:

```yaml
initContainers:
  echo-container:
    image: "busybox"
    command: ['sh', '-c', 'echo Hello from init container! && sleep 3']
```

**Comment by PaulEvans8669** [comment]
Hello,

I'll take a look at it when I have some time. My first asumption is that the given type in the values.yaml file isn't right.

```yaml
backend:
# redacted...
  volumes: {}
```

should probably be :

```yaml
backend:
# redacted...
  volumes: []
```

I will also give your solution a shot at the same time.
